#!/bin/bash

# Enhanced WAF Smoke Test with Edge Block Detection
# Original Author: realad (GitHub)
# Modifications: Adds CloudFront/WAF edge block detection, CSRF, error handling, etc.

# Check dependencies
for cmd in curl awk sed grep; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "Error: $cmd is required but not installed."
    exit 1
  fi
done

# Show usage if no arguments
if [ $# -lt 1 ]; then
  echo "Error: URL parameter is required"
  echo "Usage: $0 <URL> [-o output.md] [-H \"Header: Value\"]"
  echo "Examples:"
  echo "  $0 \"https://example.com\""
  echo "  $0 \"https://example.com/search?query=FUZZ\" -o report.md -H \"User-Agent: Custom\""
  exit 1
fi

# Helper to detect if response is blocked at edge
detect_block_origin() {
  local headers="$1"
  local body="$2"

  if echo "$headers" | grep -qiE 'x-amz-cf-id|x-amz-cf-pop|cloudfront'; then
    if echo "$body" | grep -qiE '403 ERROR|Request blocked\.|Generated by cloudfront'; then
      echo "Edge"
    fi
  fi
  echo ""
}

# URL encode
urlencode() {
  local string="$1"
  local strlen=${#string}
  local encoded=""
  local pos c o
  for ((pos=0; pos<strlen; pos++)); do
    c=${string:$pos:1}
    case "$c" in
      [-_.~a-zA-Z0-9]) o="$c" ;;
      *) printf -v o '%%%02X' "'"$c ;;
    esac
    encoded+="$o"
  done
  echo "$encoded"
}

# Percentage calc
calc_percentage() {
  awk -v n="$1" -v d="$2" 'BEGIN{ if(d==0) print 0; else printf "%.1f",(n/d)*100 }'
}

# Input URL
URL="$1"
shift || true
OUTPUT_FILE=""
HEADERS=()

# Parse options
while [ $# -gt 0 ]; do
  case "$1" in
    -o) OUTPUT_FILE="$2"; shift 2 ;;
    -H) HEADERS+=("-H" "$2"); shift 2 ;;
    *) echo "Unknown option $1"; exit 1 ;;
  esac
done

# Insert FUZZ if not present
[[ "$URL" != *FUZZ* ]] && URL="${URL}?q=FUZZ"

# Payloads and categories
PAYLOADS=(
  "' OR '1'='1"
  "<script>alert('xss')</script>"
  "../../etc/passwd"
  "| cat /etc/passwd"
  "http://169.254.169.254/latest/meta-data/"
  "{'\\$gt':''}"
  "php://filter/convert.base64-encode/resource=index.php"
  "__CSRF_POST__"
  "'\"<invalid>"
  # Hex encoded versions
  "%27%20OR%20%271%27%3D%271"
  "%3Cscript%3Ealert%28%27xss%27%29%3C%2Fscript%3E"
  "%2E%2E%2F%2E%2E%2Fetc%2Fpasswd"
  "%7C%20cat%20%2Fetc%2Fpasswd"
  "http%3A%2F%2F169.254.169.254%2Flatest%2Fmeta-data%2F"
  "%7B%27%5C%24gt%27%3A%27%27%7D"
  "php%3A%2F%2Ffilter%2Fconvert.base64-encode%2Fresource%3Dindex.php"
)

CATEGORIES=(
  "SQL Injection"
  "XSS"
  "Path Traversal"
  "Command Injection"
  "SSRF"
  "NoSQL Injection"
  "LFI"
  "CSRF"
  "Error Handling"
  # Hex encoded versions
  "SQL Injection (hex)"
  "XSS (hex)"
  "Path Traversal (hex)"
  "Command Injection (hex)"
  "SSRF (hex)"
  "NoSQL Injection (hex)"
  "LFI (hex)"
)

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Output header
printf "\n%-3s %-40s %-18s %-10s %-20s\n" "#" "Payload" "Status" "HTTP Code" "Category"
printf "%s\n" "$(printf '%0.s-' {1..100})"

results=()
i=1

for ((idx=0; idx<${#PAYLOADS[@]}; idx++)); do
  PAYLOAD="${PAYLOADS[$idx]}"
  CATEGORY="${CATEGORIES[$idx]}"

  if [[ "$PAYLOAD" == "__CSRF_POST__" ]]; then
    RESPONSE=$(curl -s -D - -X POST "${HEADERS[@]}" "$URL")
    HEADERS_OUT=$(echo "$RESPONSE" | sed -n '/^HTTP/{:a;n;/^$/!ba;p}')
    BODY_OUT=$(echo "$RESPONSE" | sed -n '/^$/,$p' | tail -n +2)
    CODE=$(echo "$RESPONSE" | awk 'NR==1{print $2}')
    ORIGIN=$(detect_block_origin "$HEADERS_OUT" "$BODY_OUT")
    DISPLAY="CSRF POST (no token)"
  else
    ENCODED=$(urlencode "$PAYLOAD")
    TARGET_URL="${URL//FUZZ/$ENCODED}"
    RESPONSE=$(curl -s -D - "${HEADERS[@]}" "$TARGET_URL")
    HEADERS_OUT=$(echo "$RESPONSE" | sed -n '/^HTTP/{:a;n;/^$/!ba;p}')
    BODY_OUT=$(echo "$RESPONSE" | sed -n '/^$/,$p' | tail -n +2)
    CODE=$(echo "$RESPONSE" | awk 'NR==1{print $2}')
    ORIGIN=$(detect_block_origin "$HEADERS_OUT" "$BODY_OUT")
    DISPLAY="${PAYLOAD:0:37}"
  fi

  if [[ "$CODE" =~ ^(403|406)$ || -n "$ORIGIN" ]]; then
    ORIGIN=${ORIGIN:-"App"}
    STATUS="${GREEN}Blocked ($ORIGIN)${NC}"
    TEXT="Blocked ($ORIGIN)"
  elif [[ "$CODE" =~ ^(2|3) ]]; then
    STATUS="${RED}Allowed${NC}"
    TEXT="Allowed"
  else
    STATUS="${YELLOW}Check${NC}"
    TEXT="Check"
  fi

  printf "%-3s %-40s %-18b %-10s %-20s\n" "$i" "$DISPLAY" "$STATUS" "$CODE" "$CATEGORY"
  results+=("$DISPLAY,$TEXT,$CODE,$CATEGORY,$ORIGIN")
  ((i++))
done

# Footer
echo -e "\n📅 Test Date: $(date)"
